import { RootLayout } from '@/components/layouts/rootLayout';
import type { Metadata } from 'next';
import type { JSXElementType, NextLayoutProps } from '@/types/components';
import './globals.css';

const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
} as const satisfies Metadata;

function Layout(props: NextLayoutProps): JSXElementType {
  return <RootLayout>{props.children}</RootLayout>;
}

export { Layout as default, metadata };
