import { Noto_Sans_JP, Roboto_Mono } from 'next/font/google';
import { Footer } from '@/components/footer';
import { Header } from '@/components/header';
import { Providers } from '@/components/providers';
import type { JSXElement, NextLayoutPropsType } from '@/types/components';
import type { Metadata } from 'next';
import './globals.css';

const notoSansJP = Noto_Sans_JP({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-noto-sans-jp'
});

const robotoMono = Roboto_Mono({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-roboto-mono'
});

export const metadata: Metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
};

export default function RootLayout(props: NextLayoutPropsType): JSXElement {
  return (
    <html className={`${notoSansJP.variable} ${robotoMono.variable}`} lang='en' suppressHydrationWarning>
      <body>
        <Providers>
          <Header />
          {props.children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
