const HOLE_COUNT = 9;
const ANIMATION_DURATION = 1.4;
const HIT_ANIMATION_DURATION = 1;
const WAIT_DURATION = 1.5;
const TOTAL_STEPS = 10;
const MAX_MOLES_PER_STEP = 3;

export { ANIMATION_DURATION, HIT_ANIMATION_DURATION, HOLE_COUNT, MAX_MOLES_PER_STEP, TOTAL_STEPS, WAIT_DURATION };
