import { Providers } from '@/components/providers';
import type { JSXElement, NextLayoutPropsType } from '@/types/components';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  'description': 'Generated by create next app',
  'title': 'Create Next App'
};

export default function RootLayout(props: NextLayoutPropsType): JSXElement {
  return (
    <html lang='en' suppressHydrationWarning>
      <body>
        <Providers>{props.children}</Providers>
      </body>
    </html>
  );
}
