services:
  portfolio:
    build:
      context: ../
      dockerfile: ./.devcontainer/portfolio-container/Dockerfile
      target: prod
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
        USER_NAME: ${USER_NAME}
        UID: ${UID}
        SYSTEM: ${SYSTEM}
        MKCERT_VERSION: ${MKCERT_VERSION}
    command: sleep infinity
    environment:
      NEXTJS_PORT: ${NEXTJS_PORT}
      STORYBOOK_PORT: ${STORYBOOK_PORT}
      NODE_VERSION: ${NODE_VERSION}
      PNPM_VERSION: ${PNPM_VERSION}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
      TZ: ${TZ}
      VERCEL_ORG_ID: ${VERCEL_ORG_ID}
      VERCEL_PROJECT_ID: ${VERCEL_PROJECT_ID}

  github-profile:
    build:
      dockerfile: ./github-profile-container/Dockerfile
      args:
        USER_NAME: ${USER_NAME}
        UID: ${UID}
    command: sleep infinity
    hostname: github-profile
    volumes:
      - type: bind
        source: ../
        target: /home/dev/workspaces
      - type: volume
        source: python_venv
        target: /home/dev/workspaces/github-profile/.venv
    environment:
      CURRENT_DATETIME: ${CURRENT_DATETIME}
      DEBUG: ${DEBUG}
      TZ: ${TZ}

  email:
    build:
      dockerfile: ./email-container/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
        PNPM_VERSION: ${PNPM_VERSION}
        USER_NAME: ${USER_NAME}
        UID: ${UID}
    command: sleep infinity
    hostname: email
    volumes:
      - type: bind
        source: ../
        target: /home/dev/workspaces
      - type: volume
        source: node_modules_email
        target: /home/dev/workspaces/email/node_modules
    environment:
      NODE_VERSION: ${NODE_VERSION}
      PNPM_VERSION: ${PNPM_VERSION}
      TZ: ${TZ}

  redis:
    image: redis:8.0.2-alpine
    hostname: redis
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:2.70.0-arm64
    hostname: redis-insight
    ports:
      - "5540:5540"
    environment:
      RI_REDIS_ALIAS: redis:6379
      RI_REDIS_HOST: redis
      RI_REDIS_PORTTZ: 6379

volumes:
  python_venv:
  node_modules_email:
