import { RootLayout } from '@/components/layouts/rootLayout';
import { Providers } from '@/components/layouts/rootLayout/providers';
import { fonts } from '@/constants/fonts';
import { arrayOfLocales } from '@/constants/i18n';
import type { Metadata } from 'next';
import type { JSXElementType, LayoutGenerateStaticParamsReturn, NextLayoutProps } from '@/types/components';
// eslint-disable-next-line import/no-relative-parent-imports
import '../globals.css';

const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
} as const satisfies Metadata;

function generateStaticParams(): LayoutGenerateStaticParamsReturn {
  return arrayOfLocales.map((lang) => {
    return { lang };
  });
}

function Layout(props: NextLayoutProps): JSXElementType {
  return (
    <html className={fonts} lang={props.params.lang} suppressHydrationWarning>
      <body>
        <Providers>
          <RootLayout lang={props.params.lang}>{props.children}</RootLayout>
        </Providers>
      </body>
    </html>
  );
}

export { Layout as default, generateStaticParams, metadata };
