import { RootLayout } from '@/components/layouts/rootLayout';
import { arrayOfLocales } from '@/constants/locales';
import type { Metadata } from 'next';
import type { GenerateStaticParamsReturn, JSXElementType, NextLayoutProps } from '@/types/components';
// eslint-disable-next-line import/no-relative-parent-imports
import '../globals.css';

const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App'
} as const satisfies Metadata;

// eslint-disable-next-line @typescript-eslint/naming-convention
function generateStaticParams(): GenerateStaticParamsReturn {
  return arrayOfLocales.map((lang) => {
    return { lang };
  });
}

function Layout(props: NextLayoutProps): JSXElementType {
  return <RootLayout params={props.params}>{props.children}</RootLayout>;
}

export { Layout as default, generateStaticParams, metadata };
