name: Email Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - email/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    timeout-minutes: 10
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: |
            email
            .github/workflows/scripts/delete_workflows_except_latest.sh

      - name: Install pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 9.15.5
          run_install: |
            - cwd: email

      - name: Deploy
        uses: cloudflare/wrangler-action@v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: email

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
