name: Email Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - email/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    timeout-minutes: 5
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy to cloudflare
        run: |
          docker build \
            --build-arg NODE_VERSION=$(grep NODE_VERSION .devcontainer/.env | cut -d '=' -f2) \
            --build-arg PNPM_VERSION=$(grep PNPM_VERSION .devcontainer/.env | cut -d '=' -f2) \
            --build-arg CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} \
            --target prod --file .devcontainer/email-container/Dockerfile .

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
