name: GitHub Profile Update

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable Debug Mode
        type: boolean
        required: false
        default: false
  repository_dispatch:
    types: [trigger-kentayamadadev]

jobs:
  Update-README:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Set current datetime as env variable
        env:
          TZ: Asia/Tokyo
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          sparse-checkout: |
            .github/workflows/scripts/delete_previous_workflow.sh
            .devcontainer/.misc/scripts/install_github_profile_packages.sh
            github-profile

      - name: Update README
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          options: -v ${{ github.workspace }}:/app
          run: |
            . ./app/.devcontainer/.misc/scripts/install_github_profile_packages.sh
            cd ./app/github-profile
            python3 -m venv ./.venv && . ./.venv/bin/activate
            make install && CURRENT_DATETIME=${{ env.CURRENT_DATETIME }} DEBUG=${{ github.event.inputs.debug }} IMGUR_CLIENT_ID=${{ secrets.IMGUR_CLIENT_ID }} make run

      - name: Commit README.md
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: ./README.md
          pull: origin main

      - name: Delete previous workflow
        run: sudo apt update && chmod +x ./.devcontainer/.misc/scripts/install_github_profile_packages.sh && sudo ./.devcontainer/.misc/scripts/install_github_profile_packages.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
