name: GitHub Profile Update

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable Debug Mode
        type: boolean
        required: false
        default: false
  repository_dispatch:
    types: [trigger-kentayamadadev]

jobs:
  Update-README:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Set current datetime as env variable
        env:
          TZ: Asia/Tokyo
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Update README.md
        run: |
          docker compose -f ./.devcontainer/docker-compose.yml up github-profile -d
          docker compose -f ./.devcontainer/docker-compose.yml exec -u root github-profile /bin/sh -c "cd /home/dev/workspaces/github-profile && python3 -m venv ./.venv && . ./.venv/bin/activate && make install && CURRENT_DATETIME=${{ env.CURRENT_DATETIME }} DEBUG=${{ github.event.inputs.debug }} GYAZO_ACCESS_TOKEN=${{ secrets.GYAZO_ACCESS_TOKEN }} make run"

      - name: Commit README.md
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: ./README.md
          pull: origin main

      - name: Delete workflows except latest
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
