name: GitHub Profile Update

on:
  workflow_dispatch:
    inputs:
      debug:
        description: Enable Debug Mode
        type: boolean
        required: false
        default: false
  repository_dispatch:
    types: [trigger-kentayamadadev]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Update-README:
    timeout-minutes: 5
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Set current datetime as env variable
        env:
          TZ: Asia/Tokyo
        run: |
          echo "CURRENT_DATETIME=$(date +'%Y-%m-%d_%H-%M-%S')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Update README.md
        run: |
          docker build \
            --tag output \
            --build-arg CURRENT_DATETIME=${{ env.CURRENT_DATETIME }} \
            --build-arg DEBUG=${{ github.event.inputs.debug }} \
            --build-arg CONTENTFUL_ACCESS_TOKEN=${{ secrets.CONTENTFUL_ACCESS_TOKEN }} \
            --target prod --file .devcontainer/github-profile-container/Dockerfile .
          docker run --name output-container output
          docker cp output-container:/app/generated/README.md ./README.md

      - name: Commit README.md
        uses: EndBug/add-and-commit@v9.1.4
        with:
          add: ./README.md
          pull: origin main

      - name: Delete workflows except latest
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
