name: OG Deployment

on:
  workflow_dispatch:
  push:
    paths:
      - og/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    timeout-minutes: 5
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy to vercel
        run: |
          docker build \
            --build-arg NODE_VERSION=22.17.0 \
            --build-arg PNPM_VERSION=10.12.4 \
            --build-arg VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }} \
            --build-arg PROJECT_NAME=og \
            --target prod --file .devcontainer/og-container/Dockerfile .

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
