name: Vercel Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ./portfolio/**

jobs:
  Deploy:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Echo
        run: |
          echo "asdadadadsd"
