name: Portfolio Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    paths:
      - portfolio/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          sparse-checkout: |
            portfolio
            .devcontainer/.env
            .github/workflows/scripts/deploy_vercel.sh
            .github/workflows/scripts/delete_workflows_except_latest.sh

      - name: Deploy to vercel
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          shell: bash
          options: -v ${{ github.workspace }}:/app
          run: |
            while ! . ./app/.github/workflows/scripts/deploy_vercel.sh \
              $(grep NODE_VERSION ./app/.devcontainer/.env | cut -d = -f2) \
              $(grep PNPM_VERSION ./app/.devcontainer/.env | cut -d = -f2) \
              ${{ secrets.VERCEL_TOKEN }};
              exit 1
            do
              echo "Deployment script failed. Retrying in 10 seconds..."
              sleep 10
            done

            echo "Deployment script succeeded!"

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
