name: Portfolio Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    paths:
      - portfolio/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          sparse-checkout: |
            portfolio
            .devcontainer/.env
            .github/workflows/scripts/deploy_vercel.sh
            .github/workflows/scripts/delete_workflows_except_latest.sh

      - name: Deploy to vercel
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          shell: bash
          options: -v ${{ github.workspace }}:/app
          run: |
            MAX_ATTEMPTS=3
            ATTEMPT=1
            SLEEP_SECONDS=20

            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "Deployment Attempt #$ATTEMPT"
              # --- Run your deployment script/command ---
              . ./app/.github/workflows/scripts/deploy_vercel.sh \
                $(grep NODE_VERSION ./app/.devcontainer/.env | cut -d = -f2) \
                $(grep PNPM_VERSION ./app/.devcontainer/.env | cut -d = -f2) \
                ${{ secrets.VERCEL_TOKEN }}
              EXIT_CODE=$?
              # ------------------------------------------

              if [ $EXIT_CODE -eq 0 ]; then
                echo "Deployment succeeded on attempt #$ATTEMPT."
                break
              else
                echo "Deployment failed on attempt #$ATTEMPT."
                if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
                  echo "Retrying in $SLEEP_SECONDS seconds..."
                  sleep $SLEEP_SECONDS
                else
                  echo "Reached max attempts ($MAX_ATTEMPTS). Failing the job."
                  exit 1
                fi
              fi

              ATTEMPT=$((ATTEMPT + 1))
            done

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
