name: Portfolio Deployment

on:
  workflow_dispatch:
  repository_dispatch:
    types: [contentful_published]
  push:
    paths:
      - portfolio/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PORTFOLIO_PROJECT_ID }}
    timeout-minutes: 10
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Deploy to vercel
        run: |
          docker compose --file ./.devcontainer/docker-compose.prod.yml up portfolio --detach
          docker compose --file ./.devcontainer/docker-compose.prod.yml exec --user root portfolio sh -c "
            set -eu

            pnpm dlx vercel link --yes --project portfolio --token=${{ secrets.VERCEL_TOKEN }} --cwd ./
            pnpm dlx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            pnpm dlx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            pnpm dlx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
          "

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_workflows_except_latest.sh && ./.github/workflows/scripts/delete_workflows_except_latest.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
