name: Portfolio Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    paths:
      - portfolio/**

jobs:
  Deployment:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4

      - name: Deploy to vercel
        run: |
          docker compose -f ./.devcontainer/docker-compose.yml up portfolio -d
          docker compose -f ./.devcontainer/docker-compose.yml exec -u root profile /bin/sh -c "pnpm install --global vercel && cd /home/dev/workspaces/profile && vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }} && vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} && vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}"

      - name: Deploy to vercel
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          shell: bash
          options: -v ${{ github.workspace }}:/app
          run: |
            . ./app/.github/workflows/scripts/deploy_vercel.sh $(grep NODE_VERSION ./app/.devcontainer/.env | cut -d = -f2) $(grep PNPM_VERSION ./app/.devcontainer/.env | cut -d = -f2) ${{ secrets.VERCEL_TOKEN }}

      - name: Delete previous workflow
        run: |
          chmod +x ./.github/workflows/scripts/delete_previous_workflow.sh && ./.github/workflows/scripts/delete_previous_workflow.sh '${{ github.workflow }}' ${{ secrets.DELETE_WORKFLOW_TOKEN }}
