name: Vercel Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
  push:
    paths:
      - portfolio/**

jobs:
  Deployment:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.4
        with:
          sparse-checkout: |
            portfolio

      - name: Update README
        uses: addnab/docker-run-action@v3
        with:
          image: debian:bookworm-slim
          options: -v ${{ github.workspace }}:/app
          run: |
            apt update && apt --yes install --no-install-recommends nodejs npm curl zsh
            zsh
            npm install --global vercel
            curl -fsSL https://get.pnpm.io/install.sh | env PNPM_VERSION=9.1.1 SHELL=/bin/zsh zsh -
            pnpm env use --global 22.2.0
            cd ./app/portfolio
            vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
            vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
            vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
